### Project plot!

Have your code for your project plot here. All data is in the ../Data/CFR_project_data folder

In [4]:
import pandas as pd 
data = pd.read_csv('../Data/CFR_project_data/naeem/mergers_0.csv')

In [5]:
data

      Time Since Last Major Merger [Gyr]  Number of Major Mergers
0                              12.361172                        1
1                              13.800000                        0
2                              13.800000                        0
3                              10.714254                        1
4                              13.800000                        0
...                                  ...                      ...
9995                           13.800000                        0
9996                           13.800000                        0
9997                           13.800000                        0
9998                           13.800000                        0
9999                           13.800000                        0

[10000 rows x 2 columns]

In [6]:
data2=pd.read_csv('../Data/CFR_project_data/naeem/mergers_0.44.csv')

In [7]:
data2

      Time Since Last Major Merger [Gyr]  Number of Major Mergers
0                              13.800000                        0
1                              13.800000                        0
2                              11.766836                        1
3                              13.800000                        0
4                              13.800000                        0
...                                  ...                      ...
9995                           13.800000                        0
9996                           13.800000                        0
9997                           13.800000                        0
9998                           13.800000                        0
9999                           13.800000                        0

[10000 rows x 2 columns]

In [8]:
data3=pd.read_csv('../Data/CFR_project_data/naeem/mergers_1.csv')

In [9]:
data3

      Time Since Last Major Merger [Gyr]  Number of Major Mergers
0                                 12.698                        3
1                                 13.800                        0
2                                 13.800                        0
3                                 13.800                        0
4                                 13.800                        0
...                                  ...                      ...
9995                              13.800                        0
9996                              13.800                        0
9997                              13.800                        0
9998                              13.800                        0
9999                              13.800                        0

[10000 rows x 2 columns]

In [14]:
num_major_mergers= data['Number of Major Mergers']

In [15]:
num_major_mergers

0       1
1       0
2       0
3       1
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Number of Major Mergers, Length: 10000, dtype: int64

In [18]:
major_merg_0 = num_major_mergers >= 1

In [19]:
print('The number of major mergers', sum(major_merg_0)) # fill in the sum after the comma

print('The total number of major mergers at 0 is', len(num_major_mergers))

The number of major mergers 240
The total number of major mergers at 0 is 10000

In [ ]:
num_major_mergers_44= data2['Number of Major Mergers']